plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'ploceus' version '1.10-SNAPSHOT'
	id 'maven-publish'
}

base {
	archivesName = project.archives_base_name
}

version = "${project.mod_version}-mc${project.minecraft_version}"
group = project.maven_group

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings ploceus.featherMappings(project.feather_build)
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	ploceus.dependOsl(project.osl_version)
}

processResources {
	inputs.property 'version', version

	filesMatching('fabric.mod.json') {
		expand 'version': version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
	it.options.release = 8
}

java {
	// Still required by IDEs such as Eclipse and Visual Studio Code
	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8

	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()
}

// If you plan to use a different file for the license, don't forget to change the file name here!
jar {
	from('LICENSE') {
		rename { "${it}_${base.archivesName.get()}" }
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	setupRepositories(repositories)
}

void setupRepositories(RepositoryHandler repositories) {
	//repositories.mavenLocal() // uncomment for testing
	def ENV = System.getenv()
	if (ENV.MAVEN_URL && ENV.MAVEN_ALIAS && ENV.MAVEN_TOKEN) {
		repositories.maven {
			url "${ENV.MAVEN_URL}/releases"
			credentials {
				username ENV.MAVEN_ALIAS
				password ENV.MAVEN_TOKEN
			}
			authentication {
				basic(BasicAuthentication)
			}
		}
	} else {
		throw GradleException("No Maven credentials specified")
	}
}
